set(SDKCONFIG_DEFAULTS
    ${SDKCONFIG_DEFAULTS}
    boards/sdkconfig.csi
)

list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="ESP32 CSI"
    MICROPY_PY_NETWORK_WLAN_CSI_DEFAULT_BUFFER_SIZE=8
)